# @package _global_

paths:
  src: /dmidata/users/malegu/4D-MLG/Croscim
  preproc: /dmidata/users/malegu/data/preproc_SST

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  # strategy: ddp
  accumulate_grad_batches: 20
  limit_train_batches: 200
  limit_val_batches: 50
  max_epochs: 100
  precision: 32
  enable_progress_bar: true
  enable_model_summary: true
  num_sanity_val_steps: 5
  log_every_n_steps: 1
  logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: /dmidata/projects/4dvarnet/results_sst_multires
    name: run
    version: ${now:%Y%m%d_%H%M%S}  # Format: 20251119_153042
    default_hp_metric: false
  callbacks:
    # - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: /dmidata/projects/4dvarnet/checkpoints_sst_multires
      monitor: val/loss
      save_top_k: 3  # Garde les 3 meilleurs modèles
      save_last: true  # Sauvegarde aussi le dernier checkpoint
      filename: '{epoch:03d}-{val/loss:.5f}'
      mode: min

datamodule:
  _target_: contrib.SST.data_multires.BaseDataModuleMultiRes
  sst_daily_paths: /nwp/sst_malegu
  covariates_paths: []
  multires: [10, 3, 1]
  precomputed: True
  mask_path: null
  domain_name: sst_multires
  res: 5.0
  pads: [False, False, False]
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2022-01-01', '2023-12-31']}  # 2022-2023 (2 ans)
    val:
      time: {_target_: builtins.slice, _args_: ['2024-01-01', '2024-06-30']}  # 2024 premier semestre
    test:
      time: {_target_: builtins.slice, _args_: ['2024-07-01', '2024-12-31']}  # 2024 second semestre
  xrds_kw:
    patch_dims: {time: 15, lat: 256, lon: 256}
    strides: {time: 7, lat: 40, lon: 40}
    test_single_day: true
    test_date_idx: 15
  dl_kw:
    batch_size: 2
    num_workers: 8
    pin_memory: true
    persistent_workers: true
    prefetch_factor: 2
  tgt_vars: ["slstr_av", "aasti_av"]
  norm_stats:
    aasti:
      av: {mean: -6.732, std: 13.734, type: zscore}
      std: {mean: 0.45, std: 0.438, type: zscore}
    avhrr:
      av: {mean: 20.34, std: 8.778, type: zscore}
      std: {mean: 0.108, std: 0.068, type: zscore}
    pmw:
      av: {mean: 18.147, std: 9.644, type: zscore}
      std: {mean: 0.094, std: 0.064, type: zscore}
    slstr:
      av: {mean: 20.429, std: 9.114, type: zscore}
      std: {mean: 0.13, std: 0.126, type: zscore}
    tgt_sst: {mean: 11.683, std: 17.667, type: zscore}
  norm_stats_covs:
    sea_ice_fraction: {min: 0.0, max: 1.0, type: minmax}

model:
  _target_: contrib.SST.models.Lit4dVarNet_SST
  persist_rw: False
  multires: [10, 3, 1]
  opt_fn: null
  tgt_vars: ["tgt_sst"]
  norm_tgt_vars: ["slstr_av", "aasti_av"]
  domain_limits: null
  rec_weight:
    patch_x1: ${optim_weight}
    patch_x3: ${optim_weight}
    patch_x10: ${optim_weight}
  optim_weight:
    patch_x1: ${optim_weight}
    patch_x3: ${optim_weight}
    patch_x10: ${optim_weight}
  prior_weight:
    patch_x1: ${optim_weight}
    patch_x3: ${optim_weight}
    patch_x10: ${optim_weight}
  frcst_lead: 0
  solver:
    _target_: contrib.SST.solver.GradSolvers
    solvers:
      solver_x1:
        _target_: contrib.SST.solver.GradSolver
        n_step: 20
        lr_grad: 1e-3
        prior_cost:
          _target_: contrib.SST.solver.BilinReconstructorPriorCost
          dim_in: 49
          dim_hidden: 96
          dim_out: 5
          bilin_quad: False
          downsamp: 2
        obs_cost: {_target_: contrib.SST.solver.BaseObsCost}
        grad_mod:
          _target_: src.models.ConvLstmGradModel
          dim_in: 5
          dim_hidden: 128
      solver_x3:
        _target_: contrib.SST.solver.GradSolver
        n_step: 15
        lr_grad: 1e-3
        prior_cost:
          _target_: contrib.SST.solver.BilinReconstructorPriorCost
          dim_in: 85
          dim_hidden: 80
          dim_out: 9
          bilin_quad: False
          downsamp: 2
        obs_cost: {_target_: contrib.SST.solver.BaseObsCost}
        grad_mod:
          _target_: src.models.ConvLstmGradModel
          dim_in: 9
          dim_hidden: 96
      solver_x10:
        _target_: contrib.SST.solver.GradSolver
        n_step: 10
        lr_grad: 1e-3
        prior_cost:
          _target_: contrib.SST.solver.BilinReconstructorPriorCost
          dim_in: 139
          dim_hidden: 64
          dim_out: 15
          bilin_quad: False
          downsamp: 2
        obs_cost: {_target_: contrib.SST.solver.BaseObsCost}
        grad_mod:
          _target_: src.models.ConvLstmGradModel
          dim_in: 15
          dim_hidden: 80
  norm_stats: ${datamodule.norm_stats}
  norm_stats_covs: ${datamodule.norm_stats_covs}

optim_weight:
  _target_: src.utils.get_linear_time_wei
  patch_dims: {time: 15, lat: 256, lon: 256}
  crop: {time: 0, lat: 28, lon: 28}
  offset: 1
  dim_order: ["time", "lat", "lon"]

metrics:
  nrmse_scores: {_target_: src.utils.rmse_based_scores_from_ds, _partial_: True}
  psd_scores: {_target_: src.utils.psd_based_scores_from_ds, _partial_: True}
  get0: {_target_: operator.itemgetter, _args_: [0]}
  get1: {_target_: operator.itemgetter, _args_: [1]}
  test_metrics:
    mu: {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.nrmse_scores}', '${metrics.get0}']}
    sig: {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.nrmse_scores}', '${metrics.get1}']}
    lx: {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.psd_scores}', '${metrics.get0}']}
    lt: {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.psd_scores}', '${metrics.get1}']}

entrypoints:
  - _target_: src.train.base_training
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
    save_dir: /dmidata/users/malegu/results
